BIN-991-Otte
binhollc/SupernovaSDK-examples pull request #2
Opened 2024-01-30 00:51 UTC by Valentin-Otte

Add the PIC18QF16Q20 protocol translator example
# Resolves

- https://focusuy.atlassian.net/browse/BIN-997

# Changes

- Creates a notebook section for the Supernova SDK tests
- Added the PIC18F16Q20 protocol translator example 
- This example includes interaction with the I2C FRAM and the onboard SPI FLASH memory. It performs read and write operations according to a variation of [this documentation](https://github.com/microchip-pic-avr-examples/pic18f16q20-i3c-multi-protocol-translator-mplab-mcc), the notebook itself explains the modification. 

# How to test

- Connect the supernova high voltage harness to the I3C 1.2V pins on the PIC18F16Q20  board
- Connect the I2C/I3C Qwiic to the I2C flash 
- Follow step by step the explanation in the PIC18QF16Q20-I3C-to-SPI-I2C-translator.ipynb juypter notebook

2024-01-31 18:46 UTC, focus-martin requested changes
Vale! I know you worked on this PR in a rush, but there is room to improve it a bit more, besides the fact that you already did a great job here.

I suggest improving the Readme description and referring to the repository of the Microchip example firmware.

I also suggest to add the Microchip repository as a submodule of this repo, something that is done with ease.

2024-01-31 18:46 UTC, focus-martin commented on notebooks/PIC18QF16Q20-I3C-to-SPI-I2C-translator/README.md
Let's enhance the description of this README file.

I think is important to mention the Microchip example repository and add a link to it.

2024-02-01 17:10 UTC, Valentin-Otte commented on notebooks/PIC18QF16Q20-I3C-to-SPI-I2C-translator/README.md
Sure, I didn't add too much information on the readme since I relied on the notebook being self-explanatory. I'll add a recap of the notebook itself on the readme file.

2024-02-06 19:49 UTC, focus-martin requested changes
- Move the file `requirements.txt` that is in the root of the repo to the folder called `scripts`
- In the readme of the PIC18F16Q20 examples, add a section or and bullet in Prerequsutes with the link to the repo of the firmware for the PIC.
- Some corrections in the readme content.

2024-02-06 19:49 UTC, focus-martin commented on notebooks/PIC18QF16Q20-I3C-to-SPI-I2C-translator/README.md
> +- PIC18QF16Q20 connected to the PIC18QF16Q20 board.
Change to:
> Microchip PIC18F16Q20 Curisosity Nano board plugged on the Binho PIC18F16Q20 Curisosity Nano baseboard.

2024-02-06 19:49 UTC, focus-martin commented on notebooks/PIC18QF16Q20-I3C-to-SPI-I2C-translator/README.md
> +- PIC18QF16Q20 board connected to the high voltage I3C bus.
Binho PIC18F16Q20 Curisosity Nano baseboard connected to the Supernova I3C HV Port through the I3C2-1.2V connector.

2024-02-06 19:49 UTC, focus-martin commented on notebooks/PIC18QF16Q20-I3C-to-SPI-I2C-translator/README.md
> +- External I2C F-RAM connected to the I2C bus from the PIC18QF16Q20 board.
External I2C F-RAM connected to the I2C bus from the Binho PIC18QF16Q20 Curisoity Nano baseboard throught the I2C-I3C1 connector.

2024-03-01 17:47 UTC, merged