BIN-1012-Navadian
binhollc/SupernovaSDK-examples pull request #3
Opened 2024-02-09 16:41 UTC by fausto-focus

Add the SPI protocol API example
# Resolves

- https://focusuy.atlassian.net/browse/BIN-1012

# Changes

- Creates a notebook section for the Supernova SDK tests to adapt to the structure already created in BIN-991
- Adds the SPI protocol API example
- This example includes tests of the different commands related to the Supernova SPI module to show the capabilities of the feature. It also includes an example of the Supernova interfacing with the Adafruit SPI FRAM, performing a write and read operation.

# How to test

- To test the commands, connect the breakout board to the Supernova and the logic analyzer in the correspondent SPI signals
- Follow step by step the explanation in the SPI-Protocol-Supernova-API.ipynb juypter notebook
- In the **Example with FRAM memory MB85RS64V** section connect the signals from the breakout board to its correspondent signals in the FRAM memory
- Execute the rest of the cells of the SPI-Protocol-Supernova-API.ipynb juypter notebook

2024-02-16 15:38 UTC, NicoleCabotImperial commented on notebooks/SPI-Protocol-API/SPI-Protocol-Supernova-API.ipynb
> +    "The first part of the demo presents all the commands allowed to use in the SPI Protocol API, showing different examples of the capabilities of this feature. The transfers and configurations util
and use a sniffer instead to verify*

2024-02-16 15:46 UTC, NicoleCabotImperial approved these changes
Approved 💯

2024-02-22 14:20 UTC, Salonso1602 requested changes
Great work! 
Ive left some small comments

2024-02-23 12:41 UTC, Salonso1602 requested changes
I think these are my final suggestions, great work!

2024-02-27 14:04 UTC, merged